/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-05 at 02:45:19 UTC 
 * Modify at your own risk.
 */

package com.team25project3.taskinfoendpoint.model;

/**
 * Model definition for TaskInfo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the taskinfoendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TaskInfo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer checked;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String dueTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lastUpdated;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer noDueTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String note;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer priority;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getChecked() {
    return checked;
  }

  /**
   * @param checked checked or {@code null} for none
   */
  public TaskInfo setChecked(java.lang.Integer checked) {
    this.checked = checked;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDueTime() {
    return dueTime;
  }

  /**
   * @param dueTime dueTime or {@code null} for none
   */
  public TaskInfo setDueTime(java.lang.String dueTime) {
    this.dueTime = dueTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public TaskInfo setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLastUpdated() {
    return lastUpdated;
  }

  /**
   * @param lastUpdated lastUpdated or {@code null} for none
   */
  public TaskInfo setLastUpdated(java.lang.String lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public TaskInfo setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNoDueTime() {
    return noDueTime;
  }

  /**
   * @param noDueTime noDueTime or {@code null} for none
   */
  public TaskInfo setNoDueTime(java.lang.Integer noDueTime) {
    this.noDueTime = noDueTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNote() {
    return note;
  }

  /**
   * @param note note or {@code null} for none
   */
  public TaskInfo setNote(java.lang.String note) {
    this.note = note;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPriority() {
    return priority;
  }

  /**
   * @param priority priority or {@code null} for none
   */
  public TaskInfo setPriority(java.lang.Integer priority) {
    this.priority = priority;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public TaskInfo setUserId(java.lang.String userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public TaskInfo set(String fieldName, Object value) {
    return (TaskInfo) super.set(fieldName, value);
  }

  @Override
  public TaskInfo clone() {
    return (TaskInfo) super.clone();
  }

}
