/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-05 at 02:45:26 UTC 
 * Modify at your own risk.
 */

package com.team25project3.userendpoint;

/**
 * Service definition for Userendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UserendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Userendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the userendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://team25p3.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "userendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Userendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Userendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getRegUserInfo".
   *
   * This request holds the parameters needed by the the userendpoint server.  After setting any
   * optional parameters, call the {@link GetRegUserInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetRegUserInfo getRegUserInfo(java.lang.String id) throws java.io.IOException {
    GetRegUserInfo result = new GetRegUserInfo(id);
    initialize(result);
    return result;
  }

  public class GetRegUserInfo extends UserendpointRequest<com.team25project3.userendpoint.model.User> {

    private static final String REST_PATH = "user/{id}";

    /**
     * Create a request for the method "getRegUserInfo".
     *
     * This request holds the parameters needed by the the userendpoint server.  After setting any
     * optional parameters, call the {@link GetRegUserInfo#execute()} method to invoke the remote
     * operation. <p> {@link GetRegUserInfo#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetRegUserInfo(java.lang.String id) {
      super(Userendpoint.this, "GET", REST_PATH, null, com.team25project3.userendpoint.model.User.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetRegUserInfo setAlt(java.lang.String alt) {
      return (GetRegUserInfo) super.setAlt(alt);
    }

    @Override
    public GetRegUserInfo setFields(java.lang.String fields) {
      return (GetRegUserInfo) super.setFields(fields);
    }

    @Override
    public GetRegUserInfo setKey(java.lang.String key) {
      return (GetRegUserInfo) super.setKey(key);
    }

    @Override
    public GetRegUserInfo setOauthToken(java.lang.String oauthToken) {
      return (GetRegUserInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public GetRegUserInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetRegUserInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetRegUserInfo setQuotaUser(java.lang.String quotaUser) {
      return (GetRegUserInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetRegUserInfo setUserIp(java.lang.String userIp) {
      return (GetRegUserInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetRegUserInfo setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetRegUserInfo set(String parameterName, Object value) {
      return (GetRegUserInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertRegUserInfo".
   *
   * This request holds the parameters needed by the the userendpoint server.  After setting any
   * optional parameters, call the {@link InsertRegUserInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.team25project3.userendpoint.model.User}
   * @return the request
   */
  public InsertRegUserInfo insertRegUserInfo(com.team25project3.userendpoint.model.User content) throws java.io.IOException {
    InsertRegUserInfo result = new InsertRegUserInfo(content);
    initialize(result);
    return result;
  }

  public class InsertRegUserInfo extends UserendpointRequest<com.team25project3.userendpoint.model.User> {

    private static final String REST_PATH = "user";

    /**
     * Create a request for the method "insertRegUserInfo".
     *
     * This request holds the parameters needed by the the userendpoint server.  After setting any
     * optional parameters, call the {@link InsertRegUserInfo#execute()} method to invoke the remote
     * operation. <p> {@link InsertRegUserInfo#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.team25project3.userendpoint.model.User}
     * @since 1.13
     */
    protected InsertRegUserInfo(com.team25project3.userendpoint.model.User content) {
      super(Userendpoint.this, "POST", REST_PATH, content, com.team25project3.userendpoint.model.User.class);
    }

    @Override
    public InsertRegUserInfo setAlt(java.lang.String alt) {
      return (InsertRegUserInfo) super.setAlt(alt);
    }

    @Override
    public InsertRegUserInfo setFields(java.lang.String fields) {
      return (InsertRegUserInfo) super.setFields(fields);
    }

    @Override
    public InsertRegUserInfo setKey(java.lang.String key) {
      return (InsertRegUserInfo) super.setKey(key);
    }

    @Override
    public InsertRegUserInfo setOauthToken(java.lang.String oauthToken) {
      return (InsertRegUserInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertRegUserInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertRegUserInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertRegUserInfo setQuotaUser(java.lang.String quotaUser) {
      return (InsertRegUserInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertRegUserInfo setUserIp(java.lang.String userIp) {
      return (InsertRegUserInfo) super.setUserIp(userIp);
    }

    @Override
    public InsertRegUserInfo set(String parameterName, Object value) {
      return (InsertRegUserInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listRegUserInfo".
   *
   * This request holds the parameters needed by the the userendpoint server.  After setting any
   * optional parameters, call the {@link ListRegUserInfo#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListRegUserInfo listRegUserInfo() throws java.io.IOException {
    ListRegUserInfo result = new ListRegUserInfo();
    initialize(result);
    return result;
  }

  public class ListRegUserInfo extends UserendpointRequest<com.team25project3.userendpoint.model.CollectionResponseUser> {

    private static final String REST_PATH = "userinfo1";

    /**
     * Create a request for the method "listRegUserInfo".
     *
     * This request holds the parameters needed by the the userendpoint server.  After setting any
     * optional parameters, call the {@link ListRegUserInfo#execute()} method to invoke the remote
     * operation. <p> {@link ListRegUserInfo#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListRegUserInfo() {
      super(Userendpoint.this, "GET", REST_PATH, null, com.team25project3.userendpoint.model.CollectionResponseUser.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListRegUserInfo setAlt(java.lang.String alt) {
      return (ListRegUserInfo) super.setAlt(alt);
    }

    @Override
    public ListRegUserInfo setFields(java.lang.String fields) {
      return (ListRegUserInfo) super.setFields(fields);
    }

    @Override
    public ListRegUserInfo setKey(java.lang.String key) {
      return (ListRegUserInfo) super.setKey(key);
    }

    @Override
    public ListRegUserInfo setOauthToken(java.lang.String oauthToken) {
      return (ListRegUserInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public ListRegUserInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListRegUserInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListRegUserInfo setQuotaUser(java.lang.String quotaUser) {
      return (ListRegUserInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListRegUserInfo setUserIp(java.lang.String userIp) {
      return (ListRegUserInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListRegUserInfo setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListRegUserInfo setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListRegUserInfo set(String parameterName, Object value) {
      return (ListRegUserInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listRegUserInfoSync".
   *
   * This request holds the parameters needed by the the userendpoint server.  After setting any
   * optional parameters, call the {@link ListRegUserInfoSync#execute()} method to invoke the remote
   * operation.
   *
   * @param synctime
   * @return the request
   */
  public ListRegUserInfoSync listRegUserInfoSync(java.lang.String synctime) throws java.io.IOException {
    ListRegUserInfoSync result = new ListRegUserInfoSync(synctime);
    initialize(result);
    return result;
  }

  public class ListRegUserInfoSync extends UserendpointRequest<com.team25project3.userendpoint.model.CollectionResponseUser> {

    private static final String REST_PATH = "userinfo2";

    /**
     * Create a request for the method "listRegUserInfoSync".
     *
     * This request holds the parameters needed by the the userendpoint server.  After setting any
     * optional parameters, call the {@link ListRegUserInfoSync#execute()} method to invoke the remote
     * operation. <p> {@link ListRegUserInfoSync#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param synctime
     * @since 1.13
     */
    protected ListRegUserInfoSync(java.lang.String synctime) {
      super(Userendpoint.this, "GET", REST_PATH, null, com.team25project3.userendpoint.model.CollectionResponseUser.class);
      this.synctime = com.google.api.client.util.Preconditions.checkNotNull(synctime, "Required parameter synctime must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListRegUserInfoSync setAlt(java.lang.String alt) {
      return (ListRegUserInfoSync) super.setAlt(alt);
    }

    @Override
    public ListRegUserInfoSync setFields(java.lang.String fields) {
      return (ListRegUserInfoSync) super.setFields(fields);
    }

    @Override
    public ListRegUserInfoSync setKey(java.lang.String key) {
      return (ListRegUserInfoSync) super.setKey(key);
    }

    @Override
    public ListRegUserInfoSync setOauthToken(java.lang.String oauthToken) {
      return (ListRegUserInfoSync) super.setOauthToken(oauthToken);
    }

    @Override
    public ListRegUserInfoSync setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListRegUserInfoSync) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListRegUserInfoSync setQuotaUser(java.lang.String quotaUser) {
      return (ListRegUserInfoSync) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListRegUserInfoSync setUserIp(java.lang.String userIp) {
      return (ListRegUserInfoSync) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String synctime;

    /**

     */
    public java.lang.String getSynctime() {
      return synctime;
    }

    public ListRegUserInfoSync setSynctime(java.lang.String synctime) {
      this.synctime = synctime;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListRegUserInfoSync setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListRegUserInfoSync setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListRegUserInfoSync set(String parameterName, Object value) {
      return (ListRegUserInfoSync) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeRegUserInfo".
   *
   * This request holds the parameters needed by the the userendpoint server.  After setting any
   * optional parameters, call the {@link RemoveRegUserInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveRegUserInfo removeRegUserInfo(java.lang.String id) throws java.io.IOException {
    RemoveRegUserInfo result = new RemoveRegUserInfo(id);
    initialize(result);
    return result;
  }

  public class RemoveRegUserInfo extends UserendpointRequest<Void> {

    private static final String REST_PATH = "reguserinfo/{id}";

    /**
     * Create a request for the method "removeRegUserInfo".
     *
     * This request holds the parameters needed by the the userendpoint server.  After setting any
     * optional parameters, call the {@link RemoveRegUserInfo#execute()} method to invoke the remote
     * operation. <p> {@link RemoveRegUserInfo#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveRegUserInfo(java.lang.String id) {
      super(Userendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveRegUserInfo setAlt(java.lang.String alt) {
      return (RemoveRegUserInfo) super.setAlt(alt);
    }

    @Override
    public RemoveRegUserInfo setFields(java.lang.String fields) {
      return (RemoveRegUserInfo) super.setFields(fields);
    }

    @Override
    public RemoveRegUserInfo setKey(java.lang.String key) {
      return (RemoveRegUserInfo) super.setKey(key);
    }

    @Override
    public RemoveRegUserInfo setOauthToken(java.lang.String oauthToken) {
      return (RemoveRegUserInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveRegUserInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveRegUserInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveRegUserInfo setQuotaUser(java.lang.String quotaUser) {
      return (RemoveRegUserInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveRegUserInfo setUserIp(java.lang.String userIp) {
      return (RemoveRegUserInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveRegUserInfo setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveRegUserInfo set(String parameterName, Object value) {
      return (RemoveRegUserInfo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateRegUserInfo".
   *
   * This request holds the parameters needed by the the userendpoint server.  After setting any
   * optional parameters, call the {@link UpdateRegUserInfo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.team25project3.userendpoint.model.User}
   * @return the request
   */
  public UpdateRegUserInfo updateRegUserInfo(com.team25project3.userendpoint.model.User content) throws java.io.IOException {
    UpdateRegUserInfo result = new UpdateRegUserInfo(content);
    initialize(result);
    return result;
  }

  public class UpdateRegUserInfo extends UserendpointRequest<com.team25project3.userendpoint.model.User> {

    private static final String REST_PATH = "user";

    /**
     * Create a request for the method "updateRegUserInfo".
     *
     * This request holds the parameters needed by the the userendpoint server.  After setting any
     * optional parameters, call the {@link UpdateRegUserInfo#execute()} method to invoke the remote
     * operation. <p> {@link UpdateRegUserInfo#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.team25project3.userendpoint.model.User}
     * @since 1.13
     */
    protected UpdateRegUserInfo(com.team25project3.userendpoint.model.User content) {
      super(Userendpoint.this, "PUT", REST_PATH, content, com.team25project3.userendpoint.model.User.class);
    }

    @Override
    public UpdateRegUserInfo setAlt(java.lang.String alt) {
      return (UpdateRegUserInfo) super.setAlt(alt);
    }

    @Override
    public UpdateRegUserInfo setFields(java.lang.String fields) {
      return (UpdateRegUserInfo) super.setFields(fields);
    }

    @Override
    public UpdateRegUserInfo setKey(java.lang.String key) {
      return (UpdateRegUserInfo) super.setKey(key);
    }

    @Override
    public UpdateRegUserInfo setOauthToken(java.lang.String oauthToken) {
      return (UpdateRegUserInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateRegUserInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateRegUserInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateRegUserInfo setQuotaUser(java.lang.String quotaUser) {
      return (UpdateRegUserInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateRegUserInfo setUserIp(java.lang.String userIp) {
      return (UpdateRegUserInfo) super.setUserIp(userIp);
    }

    @Override
    public UpdateRegUserInfo set(String parameterName, Object value) {
      return (UpdateRegUserInfo) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Userendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Userendpoint}. */
    @Override
    public Userendpoint build() {
      return new Userendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UserendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUserendpointRequestInitializer(
        UserendpointRequestInitializer userendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(userendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
